#pragma config(Motor,  port1,           FrontLeft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BackLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BackRight,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


string battery;
void pre_auton()
{
}

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}
void drive() {
	motor[FrontLeft] = vexRT[Ch3] + vexRT[Btn5U] *127 + vexRT[Btn6U] *-127;
	motor[FrontRight] = vexRT[Ch2] + vexRT[Btn5U] *-127 + vexRT[Btn6U] *127;
	motor[BackLeft] = vexRT[Ch3] + vexRT[Btn5U] *127 + vexRT[Btn6U] *-127;
	motor[BackRight] = vexRT[Ch2] + vexRT[Btn5U] *-127 + vexRT[Btn6U] *127;
}
void LCD() {
	battery = (nImmediateBatteryLevel/1000.);
	displayLCDCenteredString(0,battery);
	if(nLCDButtons == 7){
		displayLCDString(0,0,"Srry!");
	}
	else if(nLCDButtons == 6){
		displayLCDString(1,0,"Let's go bowling!");
	}
}
task usercontrol()
{
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
	while (true)
	{
		drive();
		LCD();
	}
}
