#pragma config(Sensor, in1,    Poten1,         sensorPotentiometer)
#pragma config(Sensor, in2,    Poten2,         sensorPotentiometer)
#pragma config(Sensor, in3,    ArmPoten1,      sensorPotentiometer)
#pragma config(Sensor, in4,    ArmPoten2,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  TwoRemote,      sensorTouch)
#pragma config(Sensor, dgtl2,  ,               sensorTouch)
#pragma config(Sensor, dgtl3,  ,               sensorTouch)
#pragma config(Sensor, dgtl4,  ProgrammingSkills, sensorTouch)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Sensor, dgtl6,  ,               sensorTouch)
#pragma config(Sensor, dgtl7,  LiftLimit,      sensorTouch)
#pragma config(Sensor, dgtl8,  ,               sensorTouch)
#pragma config(Sensor, dgtl9,  ,               sensorTouch)
#pragma config(Sensor, dgtl10, ,               sensorTouch)
#pragma config(Sensor, dgtl11, NearvsFar,      sensorTouch)
#pragma config(Sensor, dgtl12, LeftvsRight,    sensorTouch)
#pragma config(Sensor, I2C_1,  BackLeft,       sensorNone)
#pragma config(Sensor, I2C_2,  BackRight,      sensorNone)
#pragma config(Motor,  port1,           Claw1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BackRight,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           MidRight,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           MidLeft,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           FrontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           BackLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

int x;
int autonMoveL; //Reset variable for autonomous left wheel
int autonMoveR; // reset wheel for autonomous right wheel
int RightJoyMV; //Main Right Y
int RightJoySV; //Partner Right Y
int LeftJoyMV;  //Main Left Y
int LeftJoySV;  //Partner Left Y
int LeftJoyMH; //Main Left X
int LeftJoySH; //Partner Left X
int RightJoyMH; //Main Right X
int RightJoySH; //Partner Right X
string batteryMain; //String for lcd
string batteryPowerExpander; //String for lcd

int JoyClear(int origVal) { //intake current joystick position
	if(abs(origVal) < 10){ // if joystick is close to still just return 0
		return 0;
	}
	else{
		return origVal; //else, function properly
	}
	//Stops the idle motor sound
}

int PowerCap(int motorPower){ //intake joystick position
	if(abs(motorPower) <= 127){ //if power value is between 127 & -127 then return actual power
		return motorPower;
	}
	else if(motorPower > 127){ //if above 127, set to 127
		return 127;
	}
	else{ //if below -127, set to -127
		return -127;
	}
}

void Variables(){
	RightJoyMV = JoyClear(vexRT[Ch2]);
	RightJoySV = JoyClear(vexRT[Ch2Xmtr2]);
	LeftJoyMV = JoyClear(vexRT[Ch3]);
	LeftJoySV = JoyClear(vexRT[Ch3Xmtr2]);
	RightJoyMH = JoyClear(vexRT[Ch1]);
	RightJoySH = JoyClear(vexRT[Ch1Xmtr2]);
	LeftJoyMH = JoyClear(vexRT[Ch4]);
	LeftJoySH = JoyClear(vexRT[Ch4Xmtr2]);
	//Configure joysticks for deidling
}


void Base(){
	motor[FrontLeft] = PowerCap(LeftJoyMV);
	//Control front left wheel using left main joystick and strafe left and strafe right using upper bumpers
	motor[FrontRight] = PowerCap(RightJoyMV);
	//Control front right wheel using right main joystick and strafe left and right using upper bumpers
	motor[BackLeft] = PowerCap(LeftJoyMV);
	//Control back left wheel using left main joystick and strafe left and right using upper bumpers
	motor[BackRight] = PowerCap(RightJoyMV);
	//Control back right wheel using right main joystick and strafe left and right using upper bumpers
	motor[MidLeft] = PowerCap(LeftJoyMV);

	motor[MidRight] = PowerCap(RightJoyMV);
}

void Lift(){
	//	AngleCorrect();
	if(SensorValue[TwoRemote] == 1){ //If it is not correcting or moving to presets and two person mode is enabled
		motor[Arm1] = RightJoySV; //Control lift with 2nd remote right joystick
		motor[Arm2] = RightJoySV;
	}
	else{
		motor[Arm1]= PowerCap(vexRT[Btn6D]*-100 + vexRT[Btn5D]*100); //Control lift with Bottom bumpers
		motor[Arm2]= PowerCap(vexRT[Btn6D]*-100 + vexRT[Btn5D]*100);
	}
}

void Claw(){
	motor[Claw1] = PowerCap(vexRT[Btn6U]*-127 + vexRT[Btn5U]*127);
	motor[Claw2] = PowerCap(vexRT[Btn6U]*-127 + vexRT[Btn5U]*127);

	if(SensorValue[Poten2] >= x){
		if(SensorValue[ArmPoten1] >= x){
			motor[Claw1] = -127;
		}
		else{
			motor[Claw1] = 0;
		}
		if(SensorValue[ArmPoten2] >= x){
			motor[Claw2] = -127;
		}
		else{
			motor[Claw2] = 0;
		}
	}
}

void lcd(){
	batteryMain = (nImmediateBatteryLevel/1000.);
	if(nLCDButtons == 7){
		displayLCDString(1,0,"Let's go bowling");
	}
	else{
		displayLCDString(0,0,batteryMain);
	}
}
void Control(){
	Base();
	Lift();
	Claw();
	lcd();
}

void pre_auton(){ //Do not touch
	bStopTasksBetweenModes = true;
}

void autonL(){ //auton starting on left tile
}

void autonR(){//Right autonomous
}

void programskills(){
}

task autonomous(){
	if(SensorValue[ProgrammingSkills] == 0){
		if(SensorValue[LeftvsRight] == 1){ //Jumper
			autonR();
		}
		else{
			autonL();
		}
	}
	else{
		programskills();
	}
}

task usercontrol(){
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
	while (true)
	{
		Variables();
		Control();
	}
}
