#pragma config(Sensor, in1,    Poten1,         sensorPotentiometer)
#pragma config(Sensor, in2,    Euro,           sensorGyro)
#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Sensor, dgtl2,  AutonL,         sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  ProgrammingSkills, sensorTouch)
#pragma config(Sensor, dgtl5,  Turn,           sensorTouch)
#pragma config(Sensor, dgtl6,  Cube,           sensorTouch)
#pragma config(Sensor, dgtl7,  LiftLimit,      sensorTouch)
#pragma config(Sensor, dgtl8,  AutonR,         sensorQuadEncoder)
#pragma config(Sensor, dgtl10, Simple,         sensorTouch)
#pragma config(Sensor, dgtl11, NearvsFar,      sensorTouch)
#pragma config(Sensor, dgtl12, LeftvsRight,    sensorTouch)
#pragma config(Motor,  port1,           Arm12,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BackRight,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           MidRight,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           MidLeft,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           FrontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           BackLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Arm22,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


int autonMoveL; //Reset variable for autonomous left wheel
int autonMoveR; // reset wheel for autonomous right wheel
int RightJoyMV; //Main Right Y
int RightJoySV; //Partner Right Y
int LeftJoyMV;  //Main Left Y
int LeftJoySV;  //Partner Left Y
int LeftJoyMH; //Main Left X
int LeftJoySH; //Partner Left X
int RightJoyMH; //Main Right X
int RightJoySH; //Partner Right X
string batteryMain; //String for lcd
string batteryPowerExpander; //String for lcd

int hold = 0; //Hold

int JoyClear(int origVal) { //intake current joystick position
	if(abs(origVal) < 10){ // if joystick is close to still just return 0
		return 0;
	}
	else{
		return origVal; //else, function properly
	}
	//Stops the idle motor sound
}

int PowerCap(int motorPower){ //intake joystick position
	if(abs(motorPower) <= 127){ //if power value is between 127 & -127 then return actual power
		return motorPower;
	}
	else if(motorPower > 127){ //if above 127, set to 127
		return 127;
	}
	else{ //if below -127, set to -127
		return -127;
	}
}

void Variables(){
	RightJoyMV = JoyClear(vexRT[Ch2]);
	RightJoySV = JoyClear(vexRT[Ch2Xmtr2]);
	LeftJoyMV = JoyClear(vexRT[Ch3]);
	LeftJoySV = JoyClear(vexRT[Ch3Xmtr2]);
	RightJoyMH = JoyClear(vexRT[Ch1]);
	RightJoySH = JoyClear(vexRT[Ch1Xmtr2]);
	LeftJoyMH = JoyClear(vexRT[Ch4]);
	LeftJoySH = JoyClear(vexRT[Ch4Xmtr2]);
	//Configure joysticks for deidling
}

void Base(){
	motor[FrontLeft] = PowerCap(LeftJoyMV);
	//Control front left wheel using left main joystick and strafe left and strafe right using upper bumpers
	motor[FrontRight] = PowerCap(RightJoyMV);
	//Control front right wheel using right main joystick and strafe left and right using upper bumpers
	motor[BackLeft] = PowerCap(LeftJoyMV);
	//Control back left wheel using left main joystick and strafe left and right using upper bumpers
	motor[BackRight] = PowerCap(RightJoyMV);
	//Control back right wheel using right main joystick and strafe left and right using upper bumpers
	motor[MidLeft] = PowerCap(LeftJoyMV);
	//Control Mid motors using joysticks
	motor[MidRight] = PowerCap(RightJoyMV);
}

void Lift(){
	//	AngleCorrect();
	if (vexRT[Btn5D] != 0 || vexRT[Btn6D] != 0){ //normal operation; raise/lower if bumpers pressed
		motor[Arm1] = PowerCap(vexRT[Btn6D]*-100 + vexRT[Btn5D]*100); //Control lift with Bottom bumpers
		motor[Arm2] = PowerCap(vexRT[Btn6D]*-100 + vexRT[Btn5D]*100);
		motor[Arm12] = PowerCap(vexRT[Btn6D]*-100 + vexRT[Btn5D]*100);
		motor[Arm22] = PowerCap(vexRT[Btn6D]*-100 + vexRT[Btn5D]*100);
		hold = 0; //disable holding during manual control
	}
	else {
		if (hold == 0){ //no power to lift if hold disabled and no buttons pressed
			motor[Arm1] = 0;
			motor[Arm2] = 0;
			motor[Arm12] = 0;
			motor[Arm22] = 0;
		}
		else { //Code for when hold is activated
			if(SensorValue[Poten1] <= 2600){ //if lift is below
				motor[Arm1] = PowerCap((2900 - SensorValue[Poten1])/-10);
				motor[Arm2] = PowerCap((2900 - SensorValue[Poten1])/-10);
				motor[Arm12] = PowerCap((2900 - SensorValue[Poten1])/-10);
				motor[Arm22] = PowerCap((2900 - SensorValue[Poten1])/-10);
				} else {
				motor[Arm1] = 0;
				motor[Arm2] = 0;
				motor[Arm12] = 0;
				motor[Arm22] = 0;
			}
		}
	}
	if (hold == 0 && vexRT[Btn8D]){
		hold = 1;
	}
}

void lcd(){
	batteryMain = (nImmediateBatteryLevel/1000.);
	if(nLCDButtons ==7){
		displayLCDString(1,0,"Let's go bowling");
	}
	else{
		displayLCDString(0,0,batteryMain);
	}
}
void Control(){
	Base();
	Lift();
	lcd();
}

void pre_auton(){ //Do not touch
	bStopTasksBetweenModes = true;
}

void lDrive(int pwr){
	motor[BackLeft] = pwr;
	motor[FrontLeft] = pwr;
	motor[MidLeft] = pwr;
}

void rDrive(int pwr){
	motor[BackRight] = pwr;
	motor[FrontRight] = pwr;
	motor[MidRight] = pwr;
}

void turn(int theta){
	int initial = SensorValue[Euro];
	int desire = initial + theta;
	if(theta < 0){
		while(SensorValue[Euro] > desire + 550){
			rDrive(-55);
			lDrive(55);
		}
		while(SensorValue[Euro] > desire + 160){
			rDrive(-40);
			lDrive(40);
		}
		lDrive(0);
		rDrive(0);
		return;
	}
	if(theta > 0){
		while(SensorValue[Euro] < desire - 550){
			rDrive(55);
			lDrive(-55);
		}
		while(SensorValue[Euro] < desire - 160){
			rDrive(40);
			lDrive(-40);
		}
		lDrive(0);
		rDrive(0);
		return;
	}
}

void autonL(){ //auton starting on left tile
	if(SensorValue[Simple] == 1){
		autonMoveL = SensorValue[AutonL]; //reset encoder values
		autonMoveR = SensorValue[AutonR];
		while((SensorValue[AutonL] - autonMoveL <= 40 && SensorValue[AutonR] - autonMoveR <= 40)){//Drop lift
			motor[BackLeft] = 100;
			motor[BackRight] = 100;
			motor[FrontLeft] = 100;
			motor[MidLeft] = 100;
			motor[MidRight] = 100;
			motor[FrontRight] = 100;
		}
		autonMoveL = SensorValue[AutonL]; //reset encoder values
		autonMoveR = SensorValue[AutonR];
		while((SensorValue[AutonL] - autonMoveL >= -100 && SensorValue[AutonR] - autonMoveR >= -100)){//Drop lift
			motor[BackLeft] = -100;
			motor[BackRight] = -100;
			motor[FrontLeft] = -100;
			motor[MidLeft] = -100;
			motor[MidRight] = -100;
			motor[FrontRight] = -100;
		}
		motor[BackLeft] = 0;
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[MidLeft] = 0;
		motor[MidRight] = 0;
		motor[FrontRight] = 0;
		wait1Msec(250);
		autonMoveL = SensorValue[AutonL]; //reset encoder values
		autonMoveR = SensorValue[AutonR];
		while(SensorValue[Poten1] <= 2500){ //Lift Arm
			motor[Arm1] = -127;
			motor[Arm2] = -127;
			motor[Arm12] = -127;
			motor[Arm22] = -127;
		}
		motor[Arm1] = -20;
		motor[Arm2] = -20;
		motor[Arm12] = -20;
		motor[Arm22] = -20;
		while((SensorValue[AutonL] - autonMoveL >= -850 && SensorValue[AutonR] - autonMoveR >= -850)){//Back to fence
			motor[BackLeft] = -100;
			motor[BackRight] = -100;
			motor[FrontLeft] = -100;
			motor[MidLeft] = -100;
			motor[MidRight] = -100;
			motor[FrontRight] = -100;
		}
		motor[BackLeft] = 0;
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[MidLeft] = 0;
		motor[MidRight] = 0;
		motor[FrontRight] = 0;
		while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
			motor[Arm1] = -127;
			motor[Arm2] = -127;
			motor[Arm12] = -127;
			motor[Arm22] = -127;
		}
	}

	else if(SensorValue[NearvsFar] == 1){
		autonMoveL = SensorValue[AutonL]; //reset encoder values
		autonMoveR = SensorValue[AutonR];
		while((SensorValue[AutonL] - autonMoveL <= 70 && SensorValue[AutonR] - autonMoveR <= 70)){//Drop lift
			motor[BackLeft] = 100;
			motor[BackRight] = 100;
			motor[FrontLeft] = 100;
			motor[MidLeft] = 100;
			motor[MidRight] = 100;
			motor[FrontRight] = 100;
		}
		autonMoveL = SensorValue[AutonL]; //reset encoder values
		autonMoveR = SensorValue[AutonR];
		while((SensorValue[AutonL] - autonMoveL >= -70 && SensorValue[AutonR] - autonMoveR >= -70)){//Drop lift
			motor[BackLeft] = -100;
			motor[BackRight] = -100;
			motor[FrontLeft] = -100;
			motor[MidLeft] = -100;
			motor[MidRight] = -100;
			motor[FrontRight] = -100;
		}
		motor[BackLeft] = 0;
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[MidLeft] = 0;
		motor[MidRight] = 0;
		motor[FrontRight] = 0;
		wait1Msec(300);
		motor[Arm1] = 70;
		motor[Arm2] = 70;
		motor[Arm12] = 70;
		motor[Arm22] = 70;
		wait1Msec(200);
		autonMoveL = SensorValue[AutonL]; //reset encoder values
		autonMoveR = SensorValue[AutonR];
		while((SensorValue[AutonL] - autonMoveL <= 710 && SensorValue[AutonR] - autonMoveR <= 710)){//grab cube
			lDrive(90);
			rDrive(90);
		}
		lDrive(0);
		rDrive(0);
		wait1Msec(500);
		while(SensorValue[Poten1] <= 2650){ //Lift Arm
			motor[Arm1] = -100;
			motor[Arm2] = -100;
			motor[Arm12] = -100;
			motor[Arm22] = -100;
		}
		motor[Arm1] = -30;
		motor[Arm2] = -30;
		motor[Arm12] = -30;
		motor[Arm22] = -30;
		turn(-1100);
		while((SensorValue[AutonL] - autonMoveL >= -160 && SensorValue[AutonR] - autonMoveR >= -160)){//Backup to fence
			motor[BackLeft] = -100;
			motor[BackRight] = -100;
			motor[FrontLeft] = -100;
			motor[MidLeft] = -100;
			motor[MidRight] = -100;
			motor[FrontRight] = -100;
		}
		while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
			motor[Arm1] = -127;
			motor[Arm2] = -127;
			motor[Arm12] = -127;
			motor[Arm22] = -127;
		}
		while(SensorValue[Poten1] >= 3300){ //Lift Arm
			motor[Arm1] = 100;
			motor[Arm2] = 100;
			motor[Arm12] = 100;
			motor[Arm22] = 100;
		}
		while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
			motor[Arm1] = -127;
			motor[Arm2] = -127;
			motor[Arm12] = -127;
			motor[Arm22] = -127;
		}
		motor[Arm1] = 0;
		motor[Arm2] = 0;
		motor[Arm12] = 0;
		motor[Arm22] = 0;
	}

	else{
		autonMoveL = SensorValue[AutonL]; //reset encoder values
		autonMoveR = SensorValue[AutonR];
		while((SensorValue[AutonL] - autonMoveL <= 80)){//Forward
			motor[BackLeft] = 100;
			motor[BackRight] = 100;
			motor[FrontLeft] = 100;
			motor[MidLeft] = 100;
			motor[MidRight] = 100;
			motor[FrontRight] = 100;
		} // The main way this motion works is measuring the difference in the original encoder value and the current value
		autonMoveL = SensorValue[AutonL];
		autonMoveR = SensorValue[AutonR];//reset
		while((SensorValue[AutonL] - autonMoveL >= -150) && (SensorValue[AutonR] - autonMoveR >= -150)){//Back
			motor[BackLeft] = -80;
			motor[BackRight] = -80;
			motor[FrontLeft] = -80;
			motor[FrontRight] = -80;
			motor[MidLeft] = -80;
			motor[MidRight] = -80;
		}//Knocks dump down
		motor[BackLeft] = 0;//Stop moving
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[FrontRight] = 0;
		motor[MidLeft] = 0;
		motor[MidRight] = 0;
		wait1Msec(50);
		autonMoveL = SensorValue[AutonL];//reset
		autonMoveR = SensorValue[AutonR];

		while((SensorValue[AutonL] - autonMoveL <= 140) || (SensorValue[AutonR] - autonMoveR <= 140)){ //Forward to pick up star
			motor[BackLeft] = 100;
			motor[BackRight] = 100;
			motor[FrontLeft] = 100;
			motor[MidLeft] = 100;
			motor[MidRight] = 100;
			motor[FrontRight] = 100;
		}
		motor[BackLeft] = 0;//Stop moving
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[FrontRight] = 0;
		motor[MidLeft] = 0;
		motor[MidRight] = 0;
		while(SensorValue[Poten1] <= 2700){ //Lift Arm
			motor[Arm1] = -127;
			motor[Arm2] = -127;
			motor[Arm12] = -127;
			motor[Arm22] = -127;
		}
		motor[Arm1] = -20;//Stop arm
		motor[Arm2] = -20;
		motor[Arm12] = -20;
		motor[Arm22] = -20;
		autonMoveL = SensorValue[AutonL];//reset
		autonMoveR = SensorValue[AutonR];


		turn(850);

		/*	while((SensorValue[AutonL] - autonMoveL >= -200) && (SensorValue[AutonR] - autonMoveR <= 280)){ //Turn to face back field
		if (SensorValue[AutonL] - autonMoveL >= -200){
		lDrive(-80);
		} else {
		lDrive(0);
		}
		if (SensorValue[AutonR] - autonMoveR <= 280){
		rDrive(80);
		} else {
		rDrive(0);
		}
		}*/

		autonMoveL = SensorValue[AutonL];
		autonMoveR = SensorValue[AutonR];//reset
		while((SensorValue[AutonL] - autonMoveL >= -1500) || (SensorValue[AutonR] - autonMoveR >= -1500)){ //Back up into center wall
			motor[BackLeft] = -80;
			motor[BackRight] = -80;
			motor[FrontLeft] = -80;
			motor[FrontRight] = -80;
			motor[MidLeft] = -80;
			motor[MidRight] = -80;
		}
		motor[BackLeft] = 0;
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[FrontRight] = 0;
		motor[MidLeft] = 0;
		motor[MidRight] = 0;
		while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
			motor[Arm1] = -127;
			motor[Arm2] = -127;
			motor[Arm12] = -127;
			motor[Arm22] = -127;
		}
		wait1Msec(500);
		while(SensorValue[Poten1] >= 3700){
			motor[Arm1] = 80;
			motor[Arm2] = 80;
			motor[Arm12] = 80;
			motor[Arm22] = 80;
		}
		motor[Arm1] = 0;
		motor[Arm2] = 0;
		motor[Arm12] = 0;
		motor[Arm22] = 0;

		autonMoveL = SensorValue[AutonL]; //reset
		autonMoveR = SensorValue[AutonR];

		if(SensorValue[Turn] == 1){
			while(SensorValue[Poten1] >= 2000){ //Lower Arm
				motor[Arm1] = 127;
				motor[Arm2] = 127;
				motor[Arm12] = 127;
				motor[Arm22] = 127;
			}
			motor[Arm1] = 0;
			motor[Arm2] = 0;
			motor[Arm12] = 0;
			motor[Arm22] = 0;
			/*while((SensorValue[AutonL] - autonMoveL >= -360) && (SensorValue[AutonR] - autonMoveR <= 360)){ //Turn left
			if (SensorValue[AutonL] - autonMoveL >= -360){
			lDrive(-75);
			} else {
			lDrive(0);
			}
			if (SensorValue[AutonR] - autonMoveR <= 360){
			rDrive(75);
			} else {
			rDrive(0);
			}
			}*/

			turn(980);

			autonMoveL = SensorValue[AutonL]; //reset
			autonMoveR = SensorValue[AutonR];
			motor[BackLeft] = 0;
			motor[BackRight] = 0;
			motor[FrontLeft] = 0;
			motor[FrontRight] = 0;
			motor[MidLeft] = 0;
			motor[MidRight] = 0;
			autonMoveL = SensorValue[AutonL]; //reset
			autonMoveR = SensorValue[AutonR];
			while((SensorValue[AutonL] - autonMoveL <= 120) || (SensorValue[AutonR] - autonMoveR <= 120)){//Forward
				motor[BackLeft] = 127;
				motor[BackRight] = 127;
				motor[FrontLeft] = 127;
				motor[FrontRight] = 127;
				motor[MidLeft] = 127;
				motor[MidRight] = 127;
			}
			motor[BackLeft] = 0;
			motor[BackRight] = 0;
			motor[FrontLeft] = 0;
			motor[FrontRight] = 0;
			motor[MidLeft] = 0;
			motor[MidRight] = 0;
			while(SensorValue[LiftLimit ] == 0){ //Lift Arm to knock
				motor[Arm1] = -127;
				motor[Arm2] = -127;
				motor[Arm12] = -127;
				motor[Arm22] = -127;
			}

		}
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
}

void autonR(){//Right autonomous
	if(SensorValue[Simple] == 1){
		autonMoveL = SensorValue[AutonL]; //reset encoder values
		autonMoveR = SensorValue[AutonR];
		while((SensorValue[AutonL] - autonMoveL <= 40 && SensorValue[AutonR] - autonMoveR <= 40)){//Drop lift
			motor[BackLeft] = 100;
			motor[BackRight] = 100;
			motor[FrontLeft] = 100;
			motor[MidLeft] = 100;
			motor[MidRight] = 100;
			motor[FrontRight] = 100;
		}
		autonMoveL = SensorValue[AutonL]; //reset encoder values
		autonMoveR = SensorValue[AutonR];
		while((SensorValue[AutonL] - autonMoveL >= -100 && SensorValue[AutonR] - autonMoveR >= -100)){//Drop lift
			motor[BackLeft] = -100;
			motor[BackRight] = -100;
			motor[FrontLeft] = -100;
			motor[MidLeft] = -100;
			motor[MidRight] = -100;
			motor[FrontRight] = -100;
		}
		motor[BackLeft] = 0;
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[MidLeft] = 0;
		motor[MidRight] = 0;
		motor[FrontRight] = 0;
		wait1Msec(250);
		autonMoveL = SensorValue[AutonL]; //reset encoder values
		autonMoveR = SensorValue[AutonR];
		while(SensorValue[Poten1] <= 2500){ //Lift Arm
			motor[Arm1] = -127;
			motor[Arm2] = -127;
			motor[Arm12] = -127;
			motor[Arm22] = -127;
		}
		motor[Arm1] = -20;
		motor[Arm2] = -20;
		motor[Arm12] = -20;
		motor[Arm22] = -20;
		while((SensorValue[AutonL] - autonMoveL >= -850 && SensorValue[AutonR] - autonMoveR >= -850)){//Back to fence
			motor[BackLeft] = -100;
			motor[BackRight] = -100;
			motor[FrontLeft] = -100;
			motor[MidLeft] = -100;
			motor[MidRight] = -100;
			motor[FrontRight] = -100;
		}
		motor[BackLeft] = 0;
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[MidLeft] = 0;
		motor[MidRight] = 0;
		motor[FrontRight] = 0;
		while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
			motor[Arm1] = -127;
			motor[Arm2] = -127;
			motor[Arm12] = -127;
			motor[Arm22] = -127;
		}
	}

	else{ //non-simple auton
		autonMoveL = SensorValue[AutonL]; //reset encoder values
		autonMoveR = SensorValue[AutonR];
		while((SensorValue[AutonL] - autonMoveL <= 75)){//Forward
			motor[BackLeft] = 100;
			motor[BackRight] = 100;
			motor[FrontLeft] = 100;
			motor[MidLeft] = 100;
			motor[MidRight] = 100;
			motor[FrontRight] = 100;
		} // The main way this motion works is measuring the difference in the original encoder value and the current value
		autonMoveL = SensorValue[AutonL];
		autonMoveR = SensorValue[AutonR];//reset
		while((SensorValue[AutonL] - autonMoveL >= -150) && (SensorValue[AutonR] - autonMoveR >= -150)){//Back
			motor[BackLeft] = -80;
			motor[BackRight] = -80;
			motor[FrontLeft] = -80;
			motor[FrontRight] = -80;
			motor[MidLeft] = -80;
			motor[MidRight] = -80;
		}//Knocks dump down
		motor[BackLeft] = 0;//Stop moving
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[FrontRight] = 0;
		motor[MidLeft] = 0;
		motor[MidRight] = 0;
		wait1Msec(50);
		autonMoveL = SensorValue[AutonL];//reset
		autonMoveR = SensorValue[AutonR];

		while((SensorValue[AutonL] - autonMoveL <= 140) || (SensorValue[AutonR] - autonMoveR <= 140)){ //Forward to pick up star
			motor[BackLeft] = 100;
			motor[BackRight] = 100;
			motor[FrontLeft] = 100;
			motor[MidLeft] = 100;
			motor[MidRight] = 100;
			motor[FrontRight] = 100;
		}
		motor[BackLeft] = 0;//Stop moving
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[FrontRight] = 0;
		motor[MidLeft] = 0;
		motor[MidRight] = 0;
		wait1Msec(200);
		while(SensorValue[Poten1] <= 2700){ //Lift Arm
			motor[Arm1] = -127;
			motor[Arm2] = -127;
			motor[Arm12] = -127;
			motor[Arm22] = -127;
		}
		motor[Arm1] = -20;//Stop arm
		motor[Arm2] = -20;
		motor[Arm12] = -20;
		motor[Arm22] = -20;
		autonMoveL = SensorValue[AutonL];//reset
		autonMoveR = SensorValue[AutonR];


		turn(-920);
		wait1Msec(200);

		/*	while((SensorValue[AutonL] - autonMoveL >= -200) && (SensorValue[AutonR] - autonMoveR <= 280)){ //Turn to face back field
		if (SensorValue[AutonL] - autonMoveL >= -200){
		lDrive(-80);
		} else {
		lDrive(0);
		}
		if (SensorValue[AutonR] - autonMoveR <= 280){
		rDrive(80);
		} else {
		rDrive(0);
		}
		}*/

		autonMoveL = SensorValue[AutonL];
		autonMoveR = SensorValue[AutonR];//reset
		while((SensorValue[AutonL] - autonMoveL >= -1370) || (SensorValue[AutonR] - autonMoveR >= -1370)){ //Back up into center wall
			motor[BackLeft] = -80;
			motor[BackRight] = -80;
			motor[FrontLeft] = -80;
			motor[FrontRight] = -80;
			motor[MidLeft] = -80;
			motor[MidRight] = -80;
		}
		motor[BackLeft] = 0;
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[FrontRight] = 0;
		motor[MidLeft] = 0;
		motor[MidRight] = 0;
		while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
			motor[Arm1] = -127;
			motor[Arm2] = -127;
			motor[Arm12] = -127;
			motor[Arm22] = -127;
		}
		wait1Msec(500);
		while(SensorValue[Poten1] >= 3700){
			motor[Arm1] = 80;
			motor[Arm2] = 80;
			motor[Arm12] = 80;
			motor[Arm22] = 80;
		}
		motor[Arm1] = 0;
		motor[Arm2] = 0;
		motor[Arm12] = 0;
		motor[Arm22] = 0;

		autonMoveL = SensorValue[AutonL]; //reset
		autonMoveR = SensorValue[AutonR];

		if(SensorValue[Turn] == 1){
			while(SensorValue[Poten1] >= 2000){ //Lower Arm
				motor[Arm1] = 127;
				motor[Arm2] = 127;
				motor[Arm12] = 127;
				motor[Arm22] = 127;
			}
			motor[Arm1] = 0;
			motor[Arm2] = 0;
			motor[Arm12] = 0;
			motor[Arm22] = 0;
			/*while((SensorValue[AutonL] - autonMoveL >= -360) && (SensorValue[AutonR] - autonMoveR <= 360)){ //Turn left
			if (SensorValue[AutonL] - autonMoveL >= -360){
			lDrive(-75);
			} else {
			lDrive(0);
			}
			if (SensorValue[AutonR] - autonMoveR <= 360){
			rDrive(75);
			} else {
			rDrive(0);
			}
			}*/

			turn(-945);


			autonMoveL = SensorValue[AutonL]; //reset
			autonMoveR = SensorValue[AutonR];
			while((SensorValue[AutonL] - autonMoveL <= 120) || (SensorValue[AutonR] - autonMoveR <= 120)){//Forward
				motor[BackLeft] = 127;
				motor[BackRight] = 127;
				motor[FrontLeft] = 127;
				motor[FrontRight] = 127;
				motor[MidLeft] = 127;
				motor[MidRight] = 127;
			}
			motor[BackLeft] = 0;
			motor[BackRight] = 0;
			motor[FrontLeft] = 0;
			motor[FrontRight] = 0;
			motor[MidLeft] = 0;
			motor[MidRight] = 0;
			while(SensorValue[LiftLimit ] == 0){ //Lift Arm to knock
				motor[Arm1] = -127;
				motor[Arm2] = -127;
				motor[Arm12] = -127;
				motor[Arm22] = -127;
			}

		}
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
}

void programskills(){
	autonMoveL = SensorValue[AutonL]; //reset encoder values
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL >= -220 && SensorValue[AutonR] - autonMoveR >= -220)){//Drop lift
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[MidLeft] = -127;
		motor[MidRight] = -127;
		motor[FrontRight] = -127;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	motor[FrontRight] = 0;
	wait1Msec(1250);
	while(SensorValue[Poten1] <= 2700){ //Lift Arm
		motor[Arm1] = -127;
		motor[Arm2] = -127;
		motor[Arm12] = -127;
		motor[Arm22] = -127;
	}
	motor[Arm1] = -20;//Stop arm
	motor[Arm2] = -20;
	motor[Arm12] = -20;
	motor[Arm22] = -20;
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL >= -720) || (SensorValue[AutonR] - autonMoveR >= -720)){ //Back up into center wall
		motor[BackLeft] = -80;
		motor[BackRight] = -80;
		motor[FrontLeft] = -80;
		motor[FrontRight] = -80;
		motor[MidLeft] = -80;
		motor[MidRight] = -80;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	motor[FrontRight] = 0;
	while(SensorValue[LiftLimit ] == 0){ //Lift Arm to knock
		motor[Arm1] = -127;
		motor[Arm2] = -127;
		motor[Arm12] = -127;
		motor[Arm22] = -127;
	}
	wait1Msec(250);
	while(SensorValue[Poten1] >= 3350){
		motor[Arm1] = 80;
		motor[Arm2] = 80;
		motor[Arm12] = 80;
		motor[Arm22] = 80;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL <= 700) || (SensorValue[AutonR] - autonMoveR <= 700)){ //preload round 2
		motor[BackLeft] = 80;
		motor[BackRight] = 80;
		motor[FrontLeft] = 80;
		motor[FrontRight] = 80;
		motor[MidLeft] = 80;
		motor[MidRight] = 80;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	motor[FrontRight] = 0;
	motor[Arm1] = -20;//Stop arm
	motor[Arm2] = -20;
	motor[Arm12] = -20;
	motor[Arm22] = -20;
	wait1Msec(2000);
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL >= -800) || (SensorValue[AutonR] - autonMoveR >= -800)){ //Back up into center wall
		motor[BackLeft] = -80;
		motor[BackRight] = -80;
		motor[FrontLeft] = -80;
		motor[FrontRight] = -80;
		motor[MidLeft] = -80;
		motor[MidRight] = -80;
	}
	while(SensorValue[LiftLimit ] == 0){ //Lift Arm to knock
		motor[Arm1] = -127;
		motor[Arm2] = -127;
		motor[Arm12] = -127;
		motor[Arm22] = -127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	wait1Msec(250);
	while(SensorValue[Poten1] >= 3350){
		motor[Arm1] = 80;
		motor[Arm2] = 80;
		motor[Arm12] = 80;
		motor[Arm22] = 80;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL <= 700) || (SensorValue[AutonR] - autonMoveR <= 700)){ //preload round 3
		motor[BackLeft] = 80;
		motor[BackRight] = 80;
		motor[FrontLeft] = 80;
		motor[FrontRight] = 80;
		motor[MidLeft] = 80;
		motor[MidRight] = 80;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	motor[FrontRight] = 0;
	motor[Arm1] = -20;//Stop arm
	motor[Arm2] = -20;
	motor[Arm12] = -20;
	motor[Arm22] = -20;
	wait1Msec(1250);
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL >= -800) || (SensorValue[AutonR] - autonMoveR >= -800)){ //Back up into center wall
		motor[BackLeft] = -80;
		motor[BackRight] = -80;
		motor[FrontLeft] = -80;
		motor[FrontRight] = -80;
		motor[MidLeft] = -80;
		motor[MidRight] = -80;
	}
	while(SensorValue[LiftLimit ] == 0){ //Lift Arm to knock
		motor[Arm1] = -127;
		motor[Arm2] = -127;
		motor[Arm12] = -127;
		motor[Arm22] = -127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	while(SensorValue[Poten1] >= 3350){
		motor[Arm1] = 80;
		motor[Arm2] = 80;
		motor[Arm12] = 80;
		motor[Arm22] = 80;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL <= 700) || (SensorValue[AutonR] - autonMoveR <= 700)){ //preload round 4
		motor[BackLeft] = 80;
		motor[BackRight] = 80;
		motor[FrontLeft] = 80;
		motor[FrontRight] = 80;
		motor[MidLeft] = 80;
		motor[MidRight] = 80;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	motor[FrontRight] = 0;
	motor[Arm1] = -20;//Stop arm
	motor[Arm2] = -20;
	motor[Arm12] = -20;
	motor[Arm22] = -20;
	wait1Msec(1250);
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL >= -800) || (SensorValue[AutonR] - autonMoveR >= -800)){ //Back up into center wall
		motor[BackLeft] = -80;
		motor[BackRight] = -80;
		motor[FrontLeft] = -80;
		motor[FrontRight] = -80;
		motor[MidLeft] = -80;
		motor[MidRight] = -80;
	}
	while(SensorValue[LiftLimit ] == 0){ //Lift Arm to knock
		motor[Arm1] = -127;
		motor[Arm2] = -127;
		motor[Arm12] = -127;
		motor[Arm22] = -127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	wait1Msec(250);
	while(SensorValue[Poten1] >= 3100){
		motor[Arm1] = 80;
		motor[Arm2] = 80;
		motor[Arm12] = 80;
		motor[Arm22] = 80;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	autonMoveL = SensorValue[AutonL]; //reset encoder values
	autonMoveR = SensorValue[AutonR];

	while((SensorValue[AutonL] - autonMoveL <= 100 && SensorValue[AutonR] - autonMoveR <= 100)){//Get off fence
		motor[BackLeft] = 100;
		motor[BackRight] = 100;
		motor[FrontLeft] = 100;
		motor[MidLeft] = 100;
		motor[MidRight] = 100;
		motor[FrontRight] = 100;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	turn(840);
	autonMoveL = SensorValue[AutonL]; //reset encoder values
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL >= -120 && SensorValue[AutonR] - autonMoveR >= -120)){//Get off fence
		motor[BackLeft] = -100;
		motor[BackRight] = -100;
		motor[FrontLeft] = -100;
		motor[MidLeft] = -100;
		motor[MidRight] = -100;
		motor[FrontRight] = -100;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	while(SensorValue[Poten1] >= 2000){ //Lower Arm
		motor[Arm1] = 127;
		motor[Arm2] = 127;
		motor[Arm12] = 127;
		motor[Arm22] = 127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL <= 2800) || (SensorValue[AutonR] - autonMoveR <= 2800)){
		if (SensorValue[AutonL] - autonMoveL <= 2400){
			lDrive(116);
		}
		else {
			lDrive(70);
		}
		if (SensorValue[AutonR] - autonMoveR <= 2800){
			rDrive(127);
		}
		else {
			rDrive(0);
		}
	}
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL >= -50) || (SensorValue[AutonR] - autonMoveR >= -50)){
		motor[BackLeft] = -100;
		motor[BackRight] = -100;
		motor[FrontLeft] = -100;
		motor[FrontRight] = -100;
		motor[MidLeft] = -100;
		motor[MidRight] = -100;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	while(SensorValue[Poten1] <= 2700){ //Lift Arm
		motor[Arm1] = -127;
		motor[Arm2] = -127;
		motor[Arm12] = -127;
		motor[Arm22] = -127;
	}
	motor[Arm1] = -40;//Stop arm
	motor[Arm2] = -40;
	motor[Arm12] = -40;
	motor[Arm22] = -40;
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	turn(-940);
	while((SensorValue[AutonL] - autonMoveL >= -65) || (SensorValue[AutonR] - autonMoveR >= -65)){
		motor[BackLeft] = -100;
		motor[BackRight] = -100;
		motor[FrontLeft] = -100;
		motor[FrontRight] = -100;
		motor[MidLeft] = -100;
		motor[MidRight] = -100;
	}
	while(SensorValue[LiftLimit ] == 0){ //Lift Arm to knock
		motor[Arm1] = -127;
		motor[Arm2] = -127;
		motor[Arm12] = -127;
		motor[Arm22] = -127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	wait1Msec(150);
	while(SensorValue[Poten1] >= 2000){ //Lower Arm
		motor[Arm1] = 127;
		motor[Arm2] = 127;
		motor[Arm12] = 127;
		motor[Arm22] = 127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL <= 1200 || SensorValue[AutonR] - autonMoveR <= 1200)){//Grab 1st field cube
		motor[BackLeft] = 100;
		motor[BackRight] = 100;
		motor[FrontLeft] = 100;
		motor[MidLeft] = 100;
		motor[MidRight] = 100;
		motor[FrontRight] = 100;
	}
	autonMoveL = SensorValue[AutonL];//reset
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL >= -90 || SensorValue[AutonR] - autonMoveR >= -90)){//Grab 1st field cube
		motor[BackLeft] = -80;
		motor[BackRight] = -80;
		motor[FrontLeft] = -80;
		motor[MidLeft] = -80;
		motor[MidRight] = -80;
		motor[FrontRight] = -80;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	while(SensorValue[Poten1] <= 2700){ //Lift Arm
		motor[Arm1] = -127;
		motor[Arm2] = -127;
		motor[Arm12] = -127;
		motor[Arm22] = -127;
	}
	motor[Arm1] = -20;//Stop arm
	motor[Arm2] = -20;
	motor[Arm12] = -20;
	motor[Arm22] = -20;
	while((SensorValue[AutonL] - autonMoveL >= -800 || SensorValue[AutonR] - autonMoveR >= -800)){//Back up to fence
		motor[BackLeft] = -100;
		motor[BackRight] = -100;
		motor[FrontLeft] = -100;
		motor[MidLeft] = -100;
		motor[MidRight] = -100;
		motor[FrontRight] = -100;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	while(SensorValue[LiftLimit ] == 0){ //Lift Arm to knock
		motor[Arm1] = -127;
		motor[Arm2] = -127;
		motor[Arm12] = -127;
		motor[Arm22] = -127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	wait1Msec(150);
	while(SensorValue[Poten1] >= 3600){ //Lower Arm
		motor[Arm1] = 127;
		motor[Arm2] = 127;
		motor[Arm12] = 127;
		motor[Arm22] = 127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	autonMoveL = SensorValue[AutonL]; //reset encoder values
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL <= 1250 || SensorValue[AutonR] - autonMoveR <= 1250)){//Grab 1st field cube
		motor[BackLeft] = 127;
		motor[BackRight] = 127;
		motor[FrontLeft] = 127;
		motor[MidLeft] = 127;
		motor[MidRight] = 127;
		motor[FrontRight] = 127;
	}
	turn(-870);
	autonMoveL = SensorValue[AutonL]; //reset encoder values
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL >= -120 || SensorValue[AutonR] - autonMoveR >= -120)){//Get off fence
		motor[BackLeft] = -100;
		motor[BackRight] = -100;
		motor[FrontLeft] = -100;
		motor[MidLeft] = -100;
		motor[MidRight] = -100;
		motor[FrontRight] = -100;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	while(SensorValue[Poten1] >= 2000){ //Lower Arm
		motor[Arm1] = 127;
		motor[Arm2] = 127;
		motor[Arm12] = 127;
		motor[Arm22] = 127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	while((SensorValue[AutonL] - autonMoveL <= 2500 || SensorValue[AutonR] - autonMoveR <= 2500)){//Grab 1st field cube
		motor[BackLeft] = 116;
		motor[BackRight] = 127;
		motor[FrontLeft] = 116;
		motor[MidLeft] = 116;
		motor[MidRight] = 127;
		motor[FrontRight] = 127;
	}
	autonMoveL = SensorValue[AutonL]; //reset encoder values
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL >= -50 || SensorValue[AutonR] - autonMoveR >= -50)){//Get off fence
		motor[BackLeft] = -80;
		motor[BackRight] = -80;
		motor[FrontLeft] = -80;
		motor[MidLeft] = -80;
		motor[MidRight] = -80;
		motor[FrontRight] = -80;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	while(SensorValue[Poten1] <= 2500){ //Lift Arm
		motor[Arm1] = -127;
		motor[Arm2] = -127;
		motor[Arm12] = -127;
		motor[Arm22] = -127;
	}
	motor[Arm1] = -30;//Stop arm
	motor[Arm2] = -30;
	motor[Arm12] = -30;
	motor[Arm22] = -30;
	turn(850);
	autonMoveL = SensorValue[AutonL]; //reset encoder values
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL >= -1500 || SensorValue[AutonR] - autonMoveR >= -1500)){//Get off fence
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[MidLeft] = -127;
		motor[MidRight] = -127;
		motor[FrontRight] = -127;
	}
	motor[BackLeft] = 0;
		motor[BackRight] =  0;
		motor[FrontLeft] =  0;
		motor[MidLeft] =  0;
		motor[MidRight] =  0;
		motor[FrontRight] =  0;
	while(SensorValue[LiftLimit ] == 0){ //Lift Arm to knock
		motor[Arm1] = -127;
		motor[Arm2] = -127;
		motor[Arm12] = -127;
		motor[Arm22] = -127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	wait1Msec(150);
	while(SensorValue[Poten1] >= 2000){ //Lower Arm
		motor[Arm1] = 127;
		motor[Arm2] = 127;
		motor[Arm12] = 127;
		motor[Arm22] = 127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
	autonMoveL = SensorValue[AutonL]; //reset encoder values
	autonMoveR = SensorValue[AutonR];
	while((SensorValue[AutonL] - autonMoveL <= 70 || SensorValue[AutonR] - autonMoveR <= 70)){//Grab 1st field cube
		motor[BackLeft] = 127;
		motor[BackRight] = 127;
		motor[FrontLeft] = 127;
		motor[MidLeft] = 127;
		motor[MidRight] = 127;
		motor[FrontRight] = 127;
	}
	turn(650);

	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	motor[MidLeft] = 0;
	motor[MidRight] = 0;
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[Arm12] = 0;
	motor[Arm22] = 0;
}

task autonomous(){
	if(SensorValue[ProgrammingSkills] == 0){
		if(SensorValue[LeftvsRight] == 1){ //Jumper
			autonR();
		}
		else{
			autonL();
		}
	}
	else{
		programskills();
	}
}

task usercontrol(){
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
	while (true)
	{
		Variables();
		Control();
	}
}
