#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    Poten1,         sensorPotentiometer)
#pragma config(Sensor, in2,    Poten2,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  TwoRemote,      sensorTouch)
#pragma config(Sensor, dgtl2,  ArcadeContol,   sensorTouch)
#pragma config(Sensor, dgtl3,  Robert,         sensorTouch)
#pragma config(Sensor, dgtl4,  ProgrammingSkills,               sensorTouch)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Sensor, dgtl6,  ,               sensorTouch)
#pragma config(Sensor, dgtl7,  LiftLimit,      sensorTouch)
#pragma config(Sensor, dgtl8,  ,               sensorTouch)
#pragma config(Sensor, dgtl9,  ,               sensorTouch)
#pragma config(Sensor, dgtl10, ,               sensorTouch)
#pragma config(Sensor, dgtl11, NearvsFar,      sensorTouch)
#pragma config(Sensor, dgtl12, LeftvsRight,    sensorTouch)
#pragma config(Sensor, I2C_1,  BackLeft,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  BackRight,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BackRight,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BackLeft,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

int ArmAngle; //Preset angles
bool AngleToggle; //Disables lift while moving to presets
bool AngleToggle2; //Disables lift while correcting
int autonMoveL; //Reset variable for autonomous left wheel
int autonMoveR; // reset wheel for autonomous right wheel
int RealAngle; //Converts 2nd Potentiometer value to 1st
int RightJoyMV; //Main Right Y
int RightJoySV; //Partner Right Y
int LeftJoyMV;  //Main Left Y
int LeftJoySV;  //Partner Left Y
int LeftJoyMH; //Main Left X
int LeftJoySH; //Partner Left X
int RightJoyMH; //Main Right X
int RightJoySH; //Partner Right X
string batteryMain; //String for lcd
string batteryPowerExpander; //String for lcd

int JoyClear(int origVal) { //intake current joystick position
	if(abs(origVal) < 10){ // if joystick is close to still just return 0
		return 0;
	}
	else{
		return origVal; //else, function properly
	}
	//Stops the idle motor sound
}

int PowerCap(int motorPower){ //intake joystick position
	if(abs(motorPower) <= 127){ //if power value is between 127 & -127 then return actual power
		return motorPower;
	}
	else if(motorPower > 127){ //if above 127, set to 127
		return 127;
	}
	else{ //if below -127, set to -127
		return -127;
	}
}
void Variables(){
	RightJoyMV = JoyClear(vexRT[Ch2]);
	RightJoySV = JoyClear(vexRT[Ch2Xmtr2]);
	LeftJoyMV = JoyClear(vexRT[Ch3]);
	LeftJoySV = JoyClear(vexRT[Ch3Xmtr2]);
	RightJoyMH = JoyClear(vexRT[Ch1]);
	RightJoySH = JoyClear(vexRT[Ch1Xmtr2]);
	LeftJoyMH = JoyClear(vexRT[Ch4]);
	LeftJoySH = JoyClear(vexRT[Ch4Xmtr2]);
	//Configure joysticks for deidling
}

void AngleCorrect(){
	RealAngle = SensorValue[Poten2] - 550; //convertpoteniometer2
	if((RealAngle >= (SensorValue[Poten1] - 40)) && (RealAngle <= (SensorValue[Poten1] + 40)) && AngleToggle2 == true){ //If the Poten1 matches Poten2 then disable
		AngleToggle2 = false;
		motor[Arm2] = 0;
	}
	else if((RealAngle <= (SensorValue[Poten1] - 40))){ //If Poten2 is lower then Poten1 then raise Poten2
		AngleToggle2 = true;
		motor[Arm2] = 66;
	}
	else if((RealAngle >= (SensorValue[Poten1] + 40))){ //If Poten2 is higher then Poten1 then lower Poten2
		AngleToggle2 = true;
		motor[Arm2] = -66;
	}
}

void Base(){
	if(SensorValue[ArcadeContol] == 1){
		motor[FrontLeft] = PowerCap(RightJoyMV + RightJoyMH + vexRT[Btn5U]*120 + vexRT[Btn6U]*-120 + vexRT[Btn5D]*40 + vexRT[Btn6D]*-40);
		motor[FrontRight] = PowerCap(RightJoyMV + -RightJoyMH + vexRT[Btn5U]*-120 + vexRT[Btn6U]*120 + vexRT[Btn5D]*-40 + vexRT[Btn6D]*40);
		motor[BackLeft] = PowerCap(RightJoyMV + -RightJoyMH + vexRT[Btn5U]*120 + vexRT[Btn6U]*-120 + vexRT[Btn5D]*-40 + vexRT[Btn6D]*40);
		motor[BackRight] = PowerCap(RightJoyMV + RightJoyMH + vexRT[Btn5U]*-120 + vexRT[Btn6U]*120 + vexRT[Btn5D]*40 + vexRT[Btn6D]*-40);
		//Control Drive using horizontal and vertical axes and upper bumbers for quick turn and lower for percise turn
		//Left bumpers turns counter clockwise and right bumpers turn clockwise
	}
	else{
		motor[FrontLeft] = PowerCap(LeftJoyMV + vexRT[Btn5U]*-100 + vexRT[Btn6U]*100);
		//Control front left wheel using left main joystick and strafe left and strafe right using upper bumpers
		motor[FrontRight] = PowerCap(RightJoyMV + vexRT[Btn5U]*100 + vexRT[Btn6U]*-100);
		//Control front right wheel using right main joystick and strafe left and right using upper bumpers
		motor[BackLeft] = PowerCap(LeftJoyMV + vexRT[Btn5U]*100 + vexRT[Btn6U]*-100);
		//Control back left wheel using left main joystick and strafe left and right using upper bumpers
		motor[BackRight] = PowerCap(RightJoyMV + vexRT[Btn5U]*-100 + vexRT[Btn6U]*100);
		//Control back right wheel using right main joystick and strafe left and right using upper bumpers
	}
}

void Lift(){
	//	AngleCorrect();
	if(SensorValue[TwoRemote] == 1 && AngleToggle2 == false){ //If it is not correcting or moving to presets and two person mode is enabled
		motor[Arm1] = RightJoySV; //Control lift with 2nd remote right joystick
		motor[Arm2] = RightJoySV;
	}
	else if(AngleToggle2 == false){//If it is not correcting or moving to preset and one person mode is enabled
		if(SensorValue[ArcadeContol] == 1){
			motor[Arm1] = LeftJoyMV;
			motor[Arm2] = LeftJoyMV;
		}
		else{
			motor[Arm1]= PowerCap(vexRT[Btn6D]*100 + vexRT[Btn5D]*-100); //Control lift with Bottom bumpers
			motor[Arm2]= PowerCap(vexRT[Btn6D]*100 + vexRT[Btn5D]*-100);
		}
	}
}
void lcd(){
	batteryMain = (nImmediateBatteryLevel/1000.);
	if(nLCDButtons ==7){
		displayLCDString(1,0,"Let's go bowling");
	}
	else{
		displayLCDString(0,0,batteryMain);
	}
}
void Control(){
	Base();
	Lift();
	lcd();
}

void pre_auton(){ //Do not touch
	bStopTasksBetweenModes = true;
}
void autonL(){ //auton starting on left tile
	autonMoveL = SensorValue[I2C_1]; //reset encoder values
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL <= 80) && (SensorValue[I2C_2] - autonMoveR >= -80)){//Forward
		motor[BackLeft] = 127;
		motor[BackRight] = 127;
		motor[FrontLeft] = 127;
		motor[FrontRight] = 127;
	} // The main way this motion works is measuring the difference in the original encoder value and the current value
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];//reset
	while((SensorValue[I2C_1] - autonMoveL >= -300) && (SensorValue[I2C_2] - autonMoveR <= 300)){//Back
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = -127;
	}//Knocks dump down
	autonMoveL = SensorValue[I2C_1];//reset
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL <= 200) && (SensorValue[I2C_2] - autonMoveR >= -200)){ //Forward to pick up star
		motor[BackLeft] = 127;
		motor[BackRight] = 127;
		motor[FrontLeft] = 127;
		motor[FrontRight] = 127;
	}
	motor[BackLeft] = 0;//Stop moving
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	while(SensorValue[Poten2] >= 1500){ //Lift Arm
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;//Stop arm
	motor[Arm2] = 0;
	autonMoveL = SensorValue[I2C_1];//reset
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL >= -935) && (SensorValue[I2C_2] - autonMoveR >= -935)){ //Turn to face back field
		motor[BackLeft] = -127;
		motor[BackRight] = 127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = 127;
	}
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];//reset
	while((SensorValue[I2C_1] - autonMoveL >= -2200) && (SensorValue[I2C_2] - autonMoveR <= 2200)){ //Back up into center wall
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = -127;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	wait1Msec(750);//give time for momentum
	while(SensorValue[Poten2] <= 2800){ //Lower Arm
		motor[Arm1] = -127;
		motor[Arm2] = -127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	autonMoveL = SensorValue[I2C_1]; //reset
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL >= -875) && (SensorValue[I2C_2] - autonMoveR <= 875)){ //Turn left
		motor[BackLeft] = -127;
		motor[BackRight] = 127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = 127;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	while(SensorValue[Poten2] <= 2800){ //Lower Arm
		motor[Arm1] = -127;
		motor[Arm2] = -127;
	}

	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
}

void autonR(){//Right autonomous
	autonMoveL = SensorValue[I2C_1];//reset
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL <= 80) && (SensorValue[I2C_2] - autonMoveR >= -80)){//Forward
		motor[BackLeft] = 127;
		motor[BackRight] = 127;
		motor[FrontLeft] = 127;
		motor[FrontRight] = 127;
	}
	autonMoveL = SensorValue[I2C_1];//reset
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL >= -200) && (SensorValue[I2C_2] - autonMoveR <= 200)){//Back
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = -127;
	}//Knocks dump down
	autonMoveL = SensorValue[I2C_1];//reset
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL <= 200) && (SensorValue[I2C_2] - autonMoveR >= -200)){ //Forward to pick up star
		motor[BackLeft] = 127;
		motor[BackRight] = 127;
		motor[FrontLeft] = 127;
		motor[FrontRight] = 127;
	}
	motor[BackLeft] = 0;//Stop moving
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	while(SensorValue[Poten1] >= 1500){ //Lift Arm
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;//Stop arm
	motor[Arm2] = 0;
	autonMoveL = SensorValue[I2C_1];//reset
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL <= 935) && (SensorValue[I2C_2] - autonMoveR <= 935)){ //Turn to face back field
		motor[BackLeft] = -127;
		motor[BackRight] = 127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = 127;
	}
	autonMoveL = SensorValue[I2C_1];//reset
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL >= -2200) && (SensorValue[I2C_2] - autonMoveR <= 2200)){ //Back up into center wall
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = -127;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	while(SensorValue[Poten2] >= 1600){ //Lift Arm to dump
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	wait1Msec(250);
	while(SensorValue[Poten2] <= 2800){ //Lower Arm
		motor[Arm1] = -127;
		motor[Arm2] = -127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	/*	while((SensorValue[BackLeft] >= -3950) && (SensorValue[BackRight] >= 250)){ //Turn left
	motor[BackLeft] = -127;
	motor[BackRight] = 127;
	motor[FrontLeft] = -127;
	motor[FrontRight] = 127;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	while(SensorValue[Poten1] >= 3400){ //Lift Arm to knock
	motor[Arm1] = 90;
	motor[Arm2] = 90;
	}
	while(SensorValue[Poten2] <= 2800){ //Lower Arm
	motor[Arm1] = -127;
	motor[Arm2] = -127;
	}
	*/
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
}

void programskills(){
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL <= 80) && (SensorValue[I2C_2] - autonMoveR >= -80)){//Forward
		motor[BackLeft] = 127;
		motor[BackRight] = 127;
		motor[FrontLeft] = 127;
		motor[FrontRight] = 127;
	}
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL >= -700) && (SensorValue[I2C_2] - autonMoveR <= 700)){//Back
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = -127;
	}//Knocks dump down
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	wait1Msec(10000);
	while(SensorValue[Poten2] >= 2200){ //Lift Arm
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;//Stop arm
	motor[Arm2] = 0;
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL >= -1400) && (SensorValue[I2C_2] - autonMoveR <= 1400)){ //Back up into center wall
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = -127;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	wait1Msec(250);
	while(SensorValue[Poten2] <= 2300){ //Lower Arm
		motor[Arm1] = -127;
		motor[Arm2] = -127;
	}
	motor[Arm1] = 0;//Stop arm
	motor[Arm2] = 0;
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL <= 1400) && (SensorValue[I2C_2] - autonMoveR >= -1400)){ //Repeat
		motor[BackLeft] = 127;
		motor[BackRight] = 127;
		motor[FrontLeft] = 127;
		motor[FrontRight] = 127;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	wait1Msec(10000);
	while(SensorValue[Poten2] >= 2200){ //Lift Arm
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;//Stop arm
	motor[Arm2] = 0;
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL >= -1400) && (SensorValue[I2C_2] - autonMoveR <= 1400)){ //Back up into center wall
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = -127;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	wait1Msec(250);
	while(SensorValue[Poten2] <= 2300){ //Lower Arm
		motor[Arm1] = -127;
		motor[Arm2] = -127;
	}
	motor[Arm1] = 0;//Stop arm
	motor[Arm2] = 0;
	while((SensorValue[I2C_1] - autonMoveL <= 600) && (SensorValue[I2C_2] - autonMoveR >= -600)){ //Repeat
		motor[BackLeft] = 127;
		motor[BackRight] = 127;
		motor[FrontLeft] = 127;
		motor[FrontRight] = 127;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	wait1Msec(10000);
	while(SensorValue[Poten2] >= 2200){ //Lift Arm
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;//Stop arm
	motor[Arm2] = 0;
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL >= -1400) && (SensorValue[I2C_2] - autonMoveR <= 1400)){ //Back up into center wall
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = -127;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	wait1Msec(250);
	while(SensorValue[Poten2] <= 2300){ //Lower Arm
		motor[Arm1] = -127;
		motor[Arm2] = -127;
	}
	motor[Arm1] = 0;//Stop arm
	motor[Arm2] = 0;
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL <= 80) && (SensorValue[I2C_2] - autonMoveR >= -80)){//Forward
		motor[BackLeft] = 127;
		motor[BackRight] = 127;
		motor[FrontLeft] = 127;
		motor[FrontRight] = 127;
	}
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL >= -400) && (SensorValue[I2C_2] - autonMoveR <= 400)){//Back
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = -127;
	}//Knocks dump down
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	wait1Msec(10000);
	while(SensorValue[Poten2] >= 2200){ //Lift Arm
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;//Stop arm
	motor[Arm2] = 0;
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];
	while((SensorValue[I2C_1] - autonMoveL >= -1400) && (SensorValue[I2C_2] - autonMoveR <= 1400)){ //Back up into center wall
		motor[BackLeft] = -127;
		motor[BackRight] = -127;
		motor[FrontLeft] = -127;
		motor[FrontRight] = -127;
	}
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
	while(SensorValue[LiftLimit] == 0){ //Lift Arm to dump
		motor[Arm1] = 127;
		motor[Arm2] = 127;
	}
	motor[Arm1] = 0;
	motor[Arm2] = 0;
	wait1Msec(250);
	while(SensorValue[Poten2] <= 2300){ //Lower Arm
		motor[Arm1] = -127;
		motor[Arm2] = -127;
	}
	motor[Arm1] = 0;//Stop arm
	motor[Arm2] = 0;
	autonMoveL = SensorValue[I2C_1];
	autonMoveR = SensorValue[I2C_2];
}
task autonomous(){
	if(SensorValue[ProgrammingSkills] == 0){
		if(SensorValue[LeftvsRight] == 1){ //Jumper
			//	autonR();
		}
		else{
			autonL();
		}
	}
	else{
		programskills();
	}
}

task usercontrol(){
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
	while (true)
	{
		Control();
		Variables();
	}
}
